; Sound Effects for song Sokoban - Krusty - FX, version 2.0, generated by Arkos Tracker 2.

SokobanKrustyFX_SoundEffects
SokobanKrustyFX_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
SokobanKrustyFX_SoundEffectsDisarkPointerRegionStart0
	dw SokobanKrustyFX_SoundEffects_Sound1	; Sound effect 1.
	dw SokobanKrustyFX_SoundEffects_Sound2	; Sound effect 2.
	dw SokobanKrustyFX_SoundEffects_Sound3	; Sound effect 3.
	dw SokobanKrustyFX_SoundEffects_Sound4	; Sound effect 4.
	dw SokobanKrustyFX_SoundEffects_Sound5	; Sound effect 5.
SokobanKrustyFX_SoundEffectsDisarkPointerRegionEnd0

SokobanKrustyFX_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
SokobanKrustyFX_SoundEffects_Sound1
	db 1	; Speed

SokobanKrustyFX_SoundEffects_Sound1_Loop	db 224	; No soft, no hard. Volume: 12.
	db 2	; Noise: 2.

	db 80	; No soft, no hard. Volume: 10.

	db 192	; No soft, no hard. Volume: 8.
	db 13	; Noise: 13.

	db 80	; No soft, no hard. Volume: 10.

	db 45	; Soft only. Volume: 11.
	dw 423	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 213	; Software period.

	db 19	; Soft and Hard. Env: 10.
	dw 7	; Hardware period.
	dw 213	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 15	; Hardware period.
	dw 239	; Software period.

	db 3	; Soft and Hard. Env: 8.
	dw 9	; Hardware period.
	dw 142	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
SokobanKrustyFX_SoundEffects_Sound2
	db 0	; Speed

SokobanKrustyFX_SoundEffects_Sound2_Loop	db 184	; No soft, no hard. Volume: 7.
	db 3	; Noise: 3.

	db 216	; No soft, no hard. Volume: 11.
	db 12	; Noise: 12.

	db 192	; No soft, no hard. Volume: 8.
	db 2	; Noise: 2.

	db 176	; No soft, no hard. Volume: 6.
	db 1	; Noise: 1.

	db 192	; No soft, no hard. Volume: 8.
	db 11	; Noise: 11.

	db 4	; End of the sound effect.

; Sound effect 3.
SokobanKrustyFX_SoundEffects_Sound3
	db 0	; Speed

SokobanKrustyFX_SoundEffects_Sound3_Loop	db 232	; No soft, no hard. Volume: 13.
	db 1	; Noise: 1.

	db 120	; No soft, no hard. Volume: 15.

	db 216	; No soft, no hard. Volume: 11.
	db 1	; Noise: 1.

	db 120	; No soft, no hard. Volume: 15.

	db 57	; Soft only. Volume: 14.
	dw 628	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 778	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 878	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 978	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 1078	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
SokobanKrustyFX_SoundEffects_Sound4
	db 3	; Speed

SokobanKrustyFX_SoundEffects_Sound4_Loop	db 49	; Soft only. Volume: 12.
	dw 213	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 169	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 133	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 106	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 83	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 67	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 53	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 42	; Software period.

	db 181	; Soft only. Volume: 13.
	db 1	; Noise: 1.
	dw 34	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 27	; Software period.

	db 173	; Soft only. Volume: 11.
	db 1	; Noise: 1.
	dw 27	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 25	; Software period.

	db 169	; Soft only. Volume: 10.
	db 1	; Noise: 1.
	dw 27	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 27	; Software period.

	db 161	; Soft only. Volume: 8.
	db 1	; Noise: 1.
	dw 25	; Software period.

	db 161	; Soft only. Volume: 8.
	db 1	; Noise: 1.
	dw 27	; Software period.

	db 157	; Soft only. Volume: 7.
	db 1	; Noise: 1.
	dw 25	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 27	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
SokobanKrustyFX_SoundEffects_Sound5
	db 1	; Speed

SokobanKrustyFX_SoundEffects_Sound5_Loop	db 192	; No soft, no hard. Volume: 8.
	db 23	; Noise: 23.

	db 200	; No soft, no hard. Volume: 9.
	db 12	; Noise: 12.

	db 208	; No soft, no hard. Volume: 10.
	db 9	; Noise: 9.

	db 160	; No soft, no hard. Volume: 4.
	db 1	; Noise: 1.

	db 153	; Soft only. Volume: 6.
	db 3	; Noise: 3.
	dw 426	; Software period.

	db 4	; End of the sound effect.

SokobanKrustyFX_SoundEffectsDisarkByteRegionEnd1
